# Generated by Django 5.2.1 on 2025-05-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat_start", models.FloatField()),
                ("lat_end", models.FloatField()),
                ("long_start", models.FloatField()),
                ("long_end", models.FloatField()),
                ("length", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="RoadSpeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speed", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="traffic.roadsegment",
                    ),
                ),
            ],
        ),
    ]
