# Generated by Django 5.2.1 on 2025-05-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadspeed",
            name="road",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speed",
                to="traffic.roadsegment",
            ),
        ),
        migrations.AddConstraint(
            model_name="roadsegment",
            constraint=models.UniqueConstraint(
                fields=("lat_start", "lat_end", "long_start", "long_end", "length"),
                name="unique_road_segment",
            ),
        ),
    ]
