# Generated by Django 5.2.1 on 2025-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic", "0003_car_sensor_sensorreadings"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("license_plate",), name="unique_car_license_plate"
            ),
        ),
    ]
