# Generated by Django 5.2.1 on 2025-05-30 23:43

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic", "0004_car_unique_car_license_plate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_hex, max_length=64, unique=True
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="sensorreadings",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="traffic.car",
            ),
        ),
    ]
